"""add merchants table and tx merchant refs

Revision ID: 3cda1a26d781
Revises: 4002228dd572
Create Date: 2026-01-12 15:28:59.825890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cda1a26d781'
down_revision: Union[str, Sequence[str], None] = '4002228dd572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'merchant_key', name='uq_merchant_key')
    )
    op.create_index(op.f('ix_merchants_default_category_id'), 'merchants', ['default_category_id'], unique=False)
    op.create_index(op.f('ix_merchants_household_id'), 'merchants', ['household_id'], unique=False)
    op.create_index(op.f('ix_merchants_merchant_key'), 'merchants', ['merchant_key'], unique=False)
    op.add_column('transactions', sa.Column('merchant_key', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_key'), 'transactions', ['merchant_key'], unique=False)
    op.create_foreign_key(None, 'transactions', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_merchant_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_column('transactions', 'merchant_id')
    op.drop_column('transactions', 'merchant_key')
    op.drop_index(op.f('ix_merchants_merchant_key'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_household_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_default_category_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
