"""add budgets and monthly summaries

Revision ID: 7bc7278d306f
Revises: 3cda1a26d781
Create Date: 2026-01-12 19:45:36.386792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc7278d306f'
down_revision: Union[str, Sequence[str], None] = '3cda1a26d781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'month', 'category_id', name='uq_budget_month_category')
    )
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_household_id'), 'budgets', ['household_id'], unique=False)
    op.create_index(op.f('ix_budgets_month'), 'budgets', ['month'], unique=False)
    op.create_table('monthly_category_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('income_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expense_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'month', 'category_id', name='uq_summary_month_category')
    )
    op.create_index(op.f('ix_monthly_category_summaries_category_id'), 'monthly_category_summaries', ['category_id'], unique=False)
    op.create_index(op.f('ix_monthly_category_summaries_household_id'), 'monthly_category_summaries', ['household_id'], unique=False)
    op.create_index(op.f('ix_monthly_category_summaries_month'), 'monthly_category_summaries', ['month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_category_summaries_month'), table_name='monthly_category_summaries')
    op.drop_index(op.f('ix_monthly_category_summaries_household_id'), table_name='monthly_category_summaries')
    op.drop_index(op.f('ix_monthly_category_summaries_category_id'), table_name='monthly_category_summaries')
    op.drop_table('monthly_category_summaries')
    op.drop_index(op.f('ix_budgets_month'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_household_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
