"""add categories table and fk

Revision ID: 81ffd451440d
Revises: 9c1cc2ccb08b
Create Date: 2026-01-12 06:45:37.372275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ffd451440d'
down_revision: Union[str, Sequence[str], None] = '9c1cc2ccb08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'parent_id', 'name', name='uq_category_name')
    )
    op.create_index(op.f('ix_categories_household_id'), 'categories', ['household_id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.add_column('category_rules', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_category_rules_category'), table_name='category_rules')
    op.create_index(op.f('ix_category_rules_category_id'), 'category_rules', ['category_id'], unique=False)
    op.create_foreign_key(None, 'category_rules', 'categories', ['category_id'], ['id'])
    op.drop_column('category_rules', 'category')
    op.add_column('merchant_overrides', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_merchant_overrides_category'), table_name='merchant_overrides')
    op.create_index(op.f('ix_merchant_overrides_category_id'), 'merchant_overrides', ['category_id'], unique=False)
    op.create_foreign_key(None, 'merchant_overrides', 'categories', ['category_id'], ['id'])
    op.drop_column('merchant_overrides', 'category')
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.drop_column('transactions', 'category_id')
    op.add_column('merchant_overrides', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'merchant_overrides', type_='foreignkey')
    op.drop_index(op.f('ix_merchant_overrides_category_id'), table_name='merchant_overrides')
    op.create_index(op.f('ix_merchant_overrides_category'), 'merchant_overrides', ['category'], unique=False)
    op.drop_column('merchant_overrides', 'category_id')
    op.add_column('category_rules', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category_rules', type_='foreignkey')
    op.drop_index(op.f('ix_category_rules_category_id'), table_name='category_rules')
    op.create_index(op.f('ix_category_rules_category'), 'category_rules', ['category'], unique=False)
    op.drop_column('category_rules', 'category_id')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_household_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
