"""add categorization tables

Revision ID: 9c1cc2ccb08b
Revises: feee9a258dea
Create Date: 2026-01-12 06:33:42.091890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1cc2ccb08b'
down_revision: Union[str, Sequence[str], None] = 'feee9a258dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_rules_category'), 'category_rules', ['category'], unique=False)
    op.create_index(op.f('ix_category_rules_household_id'), 'category_rules', ['household_id'], unique=False)
    op.create_table('merchant_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_overrides_category'), 'merchant_overrides', ['category'], unique=False)
    op.create_index(op.f('ix_merchant_overrides_household_id'), 'merchant_overrides', ['household_id'], unique=False)
    op.create_index(op.f('ix_merchant_overrides_merchant_key'), 'merchant_overrides', ['merchant_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_overrides_merchant_key'), table_name='merchant_overrides')
    op.drop_index(op.f('ix_merchant_overrides_household_id'), table_name='merchant_overrides')
    op.drop_index(op.f('ix_merchant_overrides_category'), table_name='merchant_overrides')
    op.drop_table('merchant_overrides')
    op.drop_index(op.f('ix_category_rules_household_id'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_category'), table_name='category_rules')
    op.drop_table('category_rules')
    # ### end Alembic commands ###
